"""Stoic ELN — Seed data for GHS hazard phrases.

Subset of CLP Regulation Annex III + IV (H + EUH + P phrases) covering the most
commonly encountered codes in organic chemistry. Texts are the official ECHA
versions in English and Italian.

To extend: add entries below; the seed routine will skip codes that already
exist in the database.

Sources:
- https://eur-lex.europa.eu/eli/reg/2008/1272/oj  (CLP Regulation, EN+IT)
- https://echa.europa.eu/regulations/clp/clp-translation
"""

# Format: (code, category, en, it)
HAZARD_PHRASES: list[tuple[str, str, str, str]] = [
    # ─── Physical hazards (H2xx) ──────────────────────────────────────────────
    ("H200", "H", "Unstable explosive.", "Esplosivo instabile."),
    ("H201", "H", "Explosive; mass explosion hazard.", "Esplosivo; pericolo di esplosione di massa."),
    ("H220", "H", "Extremely flammable gas.", "Gas altamente infiammabile."),
    ("H221", "H", "Flammable gas.", "Gas infiammabile."),
    ("H222", "H", "Extremely flammable aerosol.", "Aerosol altamente infiammabile."),
    ("H224", "H", "Extremely flammable liquid and vapour.", "Liquido e vapori altamente infiammabili."),
    ("H225", "H", "Highly flammable liquid and vapour.", "Liquido e vapori facilmente infiammabili."),
    ("H226", "H", "Flammable liquid and vapour.", "Liquido e vapori infiammabili."),
    ("H228", "H", "Flammable solid.", "Solido infiammabile."),
    ("H242", "H", "Heating may cause a fire.", "Il riscaldamento può provocare un incendio."),
    ("H250", "H", "Catches fire spontaneously if exposed to air.",
     "Spontaneamente infiammabile all'aria."),
    ("H260", "H", "In contact with water releases flammable gases which may ignite spontaneously.",
     "A contatto con l'acqua libera gas infiammabili che possono infiammarsi spontaneamente."),
    ("H261", "H", "In contact with water releases flammable gases.",
     "A contatto con l'acqua libera gas infiammabili."),
    ("H271", "H", "May cause fire or explosion; strong oxidiser.",
     "Può provocare un incendio o un'esplosione; molto comburente."),
    ("H272", "H", "May intensify fire; oxidiser.", "Può aggravare un incendio; comburente."),
    ("H280", "H", "Contains gas under pressure; may explode if heated.",
     "Contiene gas sotto pressione; può esplodere se riscaldato."),
    ("H290", "H", "May be corrosive to metals.", "Può essere corrosivo per i metalli."),

    # ─── Health hazards (H3xx) ────────────────────────────────────────────────
    ("H300", "H", "Fatal if swallowed.", "Letale se ingerito."),
    ("H301", "H", "Toxic if swallowed.", "Tossico se ingerito."),
    ("H302", "H", "Harmful if swallowed.", "Nocivo se ingerito."),
    ("H304", "H", "May be fatal if swallowed and enters airways.",
     "Può essere letale in caso di ingestione e di penetrazione nelle vie respiratorie."),
    ("H310", "H", "Fatal in contact with skin.", "Letale per contatto con la pelle."),
    ("H311", "H", "Toxic in contact with skin.", "Tossico per contatto con la pelle."),
    ("H312", "H", "Harmful in contact with skin.", "Nocivo per contatto con la pelle."),
    ("H314", "H", "Causes severe skin burns and eye damage.",
     "Provoca gravi ustioni cutanee e gravi lesioni oculari."),
    ("H315", "H", "Causes skin irritation.", "Provoca irritazione cutanea."),
    ("H317", "H", "May cause an allergic skin reaction.",
     "Può provocare una reazione allergica cutanea."),
    ("H318", "H", "Causes serious eye damage.", "Provoca gravi lesioni oculari."),
    ("H319", "H", "Causes serious eye irritation.", "Provoca grave irritazione oculare."),
    ("H330", "H", "Fatal if inhaled.", "Letale se inalato."),
    ("H331", "H", "Toxic if inhaled.", "Tossico se inalato."),
    ("H332", "H", "Harmful if inhaled.", "Nocivo se inalato."),
    ("H334", "H", "May cause allergy or asthma symptoms or breathing difficulties if inhaled.",
     "Può provocare sintomi allergici o asmatici o difficoltà respiratorie se inalato."),
    ("H335", "H", "May cause respiratory irritation.", "Può irritare le vie respiratorie."),
    ("H336", "H", "May cause drowsiness or dizziness.", "Può provocare sonnolenza o vertigini."),
    ("H340", "H", "May cause genetic defects.", "Può provocare alterazioni genetiche."),
    ("H341", "H", "Suspected of causing genetic defects.",
     "Sospettato di provocare alterazioni genetiche."),
    ("H350", "H", "May cause cancer.", "Può provocare il cancro."),
    ("H351", "H", "Suspected of causing cancer.", "Sospettato di provocare il cancro."),
    ("H360", "H", "May damage fertility or the unborn child.",
     "Può nuocere alla fertilità o al feto."),
    ("H361", "H", "Suspected of damaging fertility or the unborn child.",
     "Sospettato di nuocere alla fertilità o al feto."),
    ("H370", "H", "Causes damage to organs.", "Provoca danni agli organi."),
    ("H371", "H", "May cause damage to organs.", "Può provocare danni agli organi."),
    ("H372", "H", "Causes damage to organs through prolonged or repeated exposure.",
     "Provoca danni agli organi in caso di esposizione prolungata o ripetuta."),
    ("H373", "H", "May cause damage to organs through prolonged or repeated exposure.",
     "Può provocare danni agli organi in caso di esposizione prolungata o ripetuta."),

    # ─── Environmental hazards (H4xx) ─────────────────────────────────────────
    ("H400", "H", "Very toxic to aquatic life.", "Molto tossico per gli organismi acquatici."),
    ("H410", "H", "Very toxic to aquatic life with long lasting effects.",
     "Molto tossico per gli organismi acquatici con effetti di lunga durata."),
    ("H411", "H", "Toxic to aquatic life with long lasting effects.",
     "Tossico per gli organismi acquatici con effetti di lunga durata."),
    ("H412", "H", "Harmful to aquatic life with long lasting effects.",
     "Nocivo per gli organismi acquatici con effetti di lunga durata."),
    ("H413", "H", "May cause long lasting harmful effects to aquatic life.",
     "Può essere nocivo per gli organismi acquatici con effetti di lunga durata."),

    # ─── EUH supplementary phrases ────────────────────────────────────────────
    ("EUH014", "EUH", "Reacts violently with water.", "Reagisce violentemente con l'acqua."),
    ("EUH019", "EUH", "May form explosive peroxides.", "Può formare perossidi esplosivi."),
    ("EUH029", "EUH", "Contact with water liberates toxic gas.",
     "A contatto con l'acqua libera gas tossici."),
    ("EUH031", "EUH", "Contact with acids liberates toxic gas.",
     "A contatto con acidi libera gas tossici."),
    ("EUH032", "EUH", "Contact with acids liberates very toxic gas.",
     "A contatto con acidi libera gas altamente tossici."),
    ("EUH066", "EUH", "Repeated exposure may cause skin dryness or cracking.",
     "L'esposizione ripetuta può provocare secchezza o screpolature della pelle."),
    ("EUH070", "EUH", "Toxic by eye contact.", "Tossico per contatto oculare."),
    ("EUH071", "EUH", "Corrosive to the respiratory tract.", "Corrosivo per le vie respiratorie."),

    # ─── Precautionary statements (P) — most common ───────────────────────────
    ("P101", "P", "If medical advice is needed, have product container or label at hand.",
     "In caso di consultazione di un medico, tenere a disposizione il contenitore o l'etichetta del prodotto."),
    ("P102", "P", "Keep out of reach of children.", "Tenere fuori dalla portata dei bambini."),
    ("P103", "P", "Read carefully and follow all instructions.",
     "Leggere attentamente e seguire tutte le istruzioni."),
    ("P201", "P", "Obtain special instructions before use.",
     "Procurarsi istruzioni specifiche prima dell'uso."),
    ("P202", "P", "Do not handle until all safety precautions have been read and understood.",
     "Non manipolare prima di aver letto e compreso tutte le avvertenze."),
    ("P210", "P", "Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking.",
     "Tenere lontano da fonti di calore, superfici calde, scintille, fiamme libere o altre fonti di accensione. Non fumare."),
    ("P211", "P", "Do not spray on an open flame or other ignition source.",
     "Non vaporizzare su una fiamma libera o altra fonte di accensione."),
    ("P220", "P", "Keep away from clothing and other combustible materials.",
     "Tenere lontano da indumenti e altri materiali combustibili."),
    ("P233", "P", "Keep container tightly closed.", "Tenere il recipiente ben chiuso."),
    ("P240", "P", "Ground and bond container and receiving equipment.",
     "Mettere a terra e a massa il contenitore e il dispositivo ricevente."),
    ("P241", "P", "Use explosion-proof electrical/ventilating/lighting equipment.",
     "Utilizzare impianti elettrici/di ventilazione/d'illuminazione antideflagranti."),
    ("P242", "P", "Use non-sparking tools.", "Utilizzare utensili antiscintillamento."),
    ("P243", "P", "Take action to prevent static discharges.",
     "Fare il necessario per impedire le scariche elettrostatiche."),
    ("P260", "P", "Do not breathe dust/fume/gas/mist/vapours/spray.",
     "Non respirare la polvere/i fumi/i gas/la nebbia/i vapori/gli aerosol."),
    ("P261", "P", "Avoid breathing dust/fume/gas/mist/vapours/spray.",
     "Evitare di respirare la polvere/i fumi/i gas/la nebbia/i vapori/gli aerosol."),
    ("P264", "P", "Wash thoroughly after handling.", "Lavare accuratamente dopo l'uso."),
    ("P270", "P", "Do not eat, drink or smoke when using this product.",
     "Non mangiare, né bere, né fumare durante l'uso."),
    ("P271", "P", "Use only outdoors or in a well-ventilated area.",
     "Utilizzare soltanto all'aperto o in luogo ben ventilato."),
    ("P273", "P", "Avoid release to the environment.", "Non disperdere nell'ambiente."),
    ("P280", "P", "Wear protective gloves/protective clothing/eye protection/face protection.",
     "Indossare guanti/indumenti protettivi/Proteggere gli occhi/il viso."),
    ("P301", "P", "IF SWALLOWED:", "IN CASO DI INGESTIONE:"),
    ("P302", "P", "IF ON SKIN:", "IN CASO DI CONTATTO CON LA PELLE:"),
    ("P304", "P", "IF INHALED:", "IN CASO DI INALAZIONE:"),
    ("P305", "P", "IF IN EYES:", "IN CASO DI CONTATTO CON GLI OCCHI:"),
    ("P308", "P", "IF exposed or concerned:", "IN CASO di esposizione o di malessere:"),
    ("P310", "P", "Immediately call a POISON CENTER/doctor.",
     "Contattare immediatamente un CENTRO ANTIVELENI/un medico."),
    ("P311", "P", "Call a POISON CENTER/doctor.", "Contattare un CENTRO ANTIVELENI/un medico."),
    ("P312", "P", "Call a POISON CENTER/doctor if you feel unwell.",
     "Contattare un CENTRO ANTIVELENI/un medico in caso di malessere."),
    ("P330", "P", "Rinse mouth.", "Sciacquare la bocca."),
    ("P331", "P", "Do NOT induce vomiting.", "NON provocare il vomito."),
    ("P332", "P", "If skin irritation occurs:", "In caso di irritazione della pelle:"),
    ("P333", "P", "If skin irritation or rash occurs:", "In caso di irritazione o eruzione della pelle:"),
    ("P337", "P", "If eye irritation persists:", "Se l'irritazione degli occhi persiste:"),
    ("P338", "P", "Remove contact lenses, if present and easy to do. Continue rinsing.",
     "Togliere le eventuali lenti a contatto se è agevole farlo. Continuare a sciacquare."),
    ("P351", "P", "Rinse cautiously with water for several minutes.",
     "Sciacquare accuratamente per parecchi minuti."),
    ("P361", "P", "Take off immediately all contaminated clothing.",
     "Togliere immediatamente tutti gli indumenti contaminati."),
    ("P362", "P", "Take off contaminated clothing.", "Togliere gli indumenti contaminati."),
    ("P363", "P", "Wash contaminated clothing before reuse.",
     "Lavare gli indumenti contaminati prima di indossarli nuovamente."),
    ("P370", "P", "In case of fire:", "In caso di incendio:"),
    ("P378", "P", "Use suitable extinguishing media.",
     "Utilizzare mezzi di estinzione appropriati."),
    ("P391", "P", "Collect spillage.", "Raccogliere il materiale fuoriuscito."),
    ("P403", "P", "Store in a well-ventilated place.", "Conservare in luogo ben ventilato."),
    ("P404", "P", "Store in a closed container.", "Conservare in un recipiente chiuso."),
    ("P405", "P", "Store locked up.", "Conservare sotto chiave."),
    ("P410", "P", "Protect from sunlight.", "Proteggere dai raggi solari."),
    ("P411", "P", "Store at temperatures not exceeding the specified value.",
     "Conservare a temperature non superiori al valore specificato."),
    ("P420", "P", "Store separately.", "Conservare separatamente."),
    ("P501", "P", "Dispose of contents/container in accordance with local regulations.",
     "Smaltire il prodotto/recipiente in conformità alla normativa locale."),
]
