"""Seed data: a starter catalogue of common laboratory substances.

These are loaded once at first DB initialization. Data values are taken from
PubChem and CRC Handbook of Chemistry and Physics, double-checked manually.
Idempotent: substances with matching InChIKey are skipped.
"""

# Each entry is a dict matching the Substance model fields.
# Conventions:
#   - Names are the most common laboratory short form (e.g. "DCM", not "dichloromethane")
#   - is_solvent=True means dosing in mL by default
#   - GHS data based on supplier SDS averages — adjust per actual supplier as needed

SUBSTANCES: list[dict] = [
    # ─── Solvents ─────────────────────────────────────────────────────────────
    {
        "name": "Water",
        "iupac_name": "oxidane",
        "cas_number": "7732-18-5",
        "molecular_formula": "H2O",
        "molecular_weight": 18.015,
        "smiles": "O",
        "inchi": "InChI=1S/H2O/h1H2",
        "inchi_key": "XLYOFNOQVPJJNP-UHFFFAOYSA-N",
        "density": 1.0,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": 0.0,
        "boiling_point_c": 100.0,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
    },
    {
        "name": "Methanol",
        "iupac_name": "methanol",
        "cas_number": "67-56-1",
        "molecular_formula": "CH4O",
        "molecular_weight": 32.04,
        "smiles": "CO",
        "inchi": "InChI=1S/CH4O/c1-2/h2H,1H3",
        "inchi_key": "OKKJLVBELUTLKV-UHFFFAOYSA-N",
        "density": 0.792,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -98.0,
        "boiling_point_c": 64.7,
        "ghs_pictograms": ["GHS02", "GHS06", "GHS08"],
        "h_phrases": ["H225", "H301", "H311", "H331", "H370"],
        "p_phrases": ["P210", "P233", "P280", "P301", "P310"],
    },
    {
        "name": "Ethanol",
        "iupac_name": "ethanol",
        "cas_number": "64-17-5",
        "molecular_formula": "C2H6O",
        "molecular_weight": 46.07,
        "smiles": "CCO",
        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
        "inchi_key": "LFQSCWFLJHTTHZ-UHFFFAOYSA-N",
        "density": 0.789,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -114.1,
        "boiling_point_c": 78.4,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H319"],
        "p_phrases": ["P210", "P233", "P280", "P305", "P338"],
    },
    {
        "name": "Isopropanol",
        "iupac_name": "propan-2-ol",
        "cas_number": "67-63-0",
        "molecular_formula": "C3H8O",
        "molecular_weight": 60.10,
        "smiles": "CC(C)O",
        "inchi": "InChI=1S/C3H8O/c1-3(2)4/h3-4H,1-2H3",
        "inchi_key": "KFZMGEQAYNKOFK-UHFFFAOYSA-N",
        "density": 0.786,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -89.0,
        "boiling_point_c": 82.6,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H319", "H336"],
        "p_phrases": ["P210", "P233", "P280", "P305", "P338"],
    },
    {
        "name": "Acetone",
        "iupac_name": "propan-2-one",
        "cas_number": "67-64-1",
        "molecular_formula": "C3H6O",
        "molecular_weight": 58.08,
        "smiles": "CC(=O)C",
        "inchi": "InChI=1S/C3H6O/c1-3(2)4/h1-2H3",
        "inchi_key": "CSCPPACGZOOCGX-UHFFFAOYSA-N",
        "density": 0.791,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -94.7,
        "boiling_point_c": 56.0,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H319", "H336"],
        "p_phrases": ["P210", "P233", "P280", "P305", "P338"],
    },
    {
        "name": "Acetonitrile",
        "iupac_name": "acetonitrile",
        "cas_number": "75-05-8",
        "molecular_formula": "C2H3N",
        "molecular_weight": 41.05,
        "smiles": "CC#N",
        "inchi": "InChI=1S/C2H3N/c1-2-3/h1H3",
        "inchi_key": "WEVYAHXRMPXWCK-UHFFFAOYSA-N",
        "density": 0.786,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -45.0,
        "boiling_point_c": 81.6,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H302", "H312", "H319", "H332"],
        "p_phrases": ["P210", "P280", "P305", "P338"],
    },
    {
        "name": "DCM",
        "iupac_name": "dichloromethane",
        "cas_number": "75-09-2",
        "molecular_formula": "CH2Cl2",
        "molecular_weight": 84.93,
        "smiles": "C(Cl)Cl",
        "inchi": "InChI=1S/CH2Cl2/c2-1-3/h1H2",
        "inchi_key": "YMWUJEATGCHHMB-UHFFFAOYSA-N",
        "density": 1.325,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -97.0,
        "boiling_point_c": 39.6,
        "ghs_pictograms": ["GHS07", "GHS08"],
        "h_phrases": ["H315", "H319", "H335", "H336", "H351", "H373"],
        "p_phrases": ["P261", "P281", "P305", "P338"],
    },
    {
        "name": "Chloroform",
        "iupac_name": "trichloromethane",
        "cas_number": "67-66-3",
        "molecular_formula": "CHCl3",
        "molecular_weight": 119.38,
        "smiles": "C(Cl)(Cl)Cl",
        "inchi": "InChI=1S/CHCl3/c2-1(3)4/h1H",
        "inchi_key": "HEDRZPFGACZZDS-UHFFFAOYSA-N",
        "density": 1.483,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -63.5,
        "boiling_point_c": 61.2,
        "ghs_pictograms": ["GHS07", "GHS08"],
        "h_phrases": ["H302", "H315", "H319", "H331", "H336", "H351", "H361", "H372"],
        "p_phrases": ["P261", "P281", "P305", "P338"],
    },
    {
        "name": "Ethyl acetate",
        "iupac_name": "ethyl acetate",
        "cas_number": "141-78-6",
        "molecular_formula": "C4H8O2",
        "molecular_weight": 88.11,
        "smiles": "CCOC(=O)C",
        "inchi": "InChI=1S/C4H8O2/c1-3-6-4(2)5/h3H2,1-2H3",
        "inchi_key": "XEKOWRVHYACXOJ-UHFFFAOYSA-N",
        "density": 0.902,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -83.6,
        "boiling_point_c": 77.1,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H319", "H336"],
        "p_phrases": ["P210", "P233", "P280", "P305", "P338"],
    },
    {
        "name": "Diethyl ether",
        "iupac_name": "ethoxyethane",
        "cas_number": "60-29-7",
        "molecular_formula": "C4H10O",
        "molecular_weight": 74.12,
        "smiles": "CCOCC",
        "inchi": "InChI=1S/C4H10O/c1-3-5-4-2/h3-4H2,1-2H3",
        "inchi_key": "RTZKZFJDLAIYFH-UHFFFAOYSA-N",
        "density": 0.713,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -116.3,
        "boiling_point_c": 34.6,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H224", "H302", "H336"],
        "p_phrases": ["P210", "P233", "P280"],
        "notes": "Forms explosive peroxides on storage. Test before distilling.",
    },
    {
        "name": "THF",
        "iupac_name": "oxolane",
        "cas_number": "109-99-9",
        "molecular_formula": "C4H8O",
        "molecular_weight": 72.11,
        "smiles": "C1CCOC1",
        "inchi": "InChI=1S/C4H8O/c1-2-4-5-3-1/h1-4H2",
        "inchi_key": "WYURNTSHIVDZCO-UHFFFAOYSA-N",
        "density": 0.889,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -108.4,
        "boiling_point_c": 66.0,
        "ghs_pictograms": ["GHS02", "GHS07", "GHS08"],
        "h_phrases": ["H225", "H319", "H335", "H351"],
        "p_phrases": ["P210", "P280", "P305", "P338"],
        "notes": "Forms explosive peroxides on storage. Test before distilling.",
    },
    {
        "name": "Toluene",
        "iupac_name": "methylbenzene",
        "cas_number": "108-88-3",
        "molecular_formula": "C7H8",
        "molecular_weight": 92.14,
        "smiles": "Cc1ccccc1",
        "inchi": "InChI=1S/C7H8/c1-7-5-3-2-4-6-7/h2-6H,1H3",
        "inchi_key": "YXFVVABEGXRONW-UHFFFAOYSA-N",
        "density": 0.867,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -95.0,
        "boiling_point_c": 110.6,
        "ghs_pictograms": ["GHS02", "GHS07", "GHS08"],
        "h_phrases": ["H225", "H304", "H315", "H336", "H361", "H373"],
        "p_phrases": ["P210", "P280", "P301", "P331"],
    },
    {
        "name": "Hexane",
        "iupac_name": "hexane",
        "cas_number": "110-54-3",
        "molecular_formula": "C6H14",
        "molecular_weight": 86.18,
        "smiles": "CCCCCC",
        "inchi": "InChI=1S/C6H14/c1-3-5-6-4-2/h3-6H2,1-2H3",
        "inchi_key": "VLKZOEOYAKHREP-UHFFFAOYSA-N",
        "density": 0.660,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -95.3,
        "boiling_point_c": 68.7,
        "ghs_pictograms": ["GHS02", "GHS07", "GHS08", "GHS09"],
        "h_phrases": ["H225", "H304", "H315", "H336", "H361", "H373", "H411"],
        "p_phrases": ["P210", "P273", "P301", "P331"],
    },
    {
        "name": "DMF",
        "iupac_name": "N,N-dimethylformamide",
        "cas_number": "68-12-2",
        "molecular_formula": "C3H7NO",
        "molecular_weight": 73.09,
        "smiles": "CN(C)C=O",
        "inchi": "InChI=1S/C3H7NO/c1-4(2)3-5/h3H,1-2H3",
        "inchi_key": "ZMXDDKWLCZADIW-UHFFFAOYSA-N",
        "density": 0.944,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -61.0,
        "boiling_point_c": 153.0,
        "ghs_pictograms": ["GHS07", "GHS08"],
        "h_phrases": ["H226", "H312", "H319", "H332", "H360"],
        "p_phrases": ["P201", "P280", "P305", "P338"],
    },
    {
        "name": "DMSO",
        "iupac_name": "dimethyl sulfoxide",
        "cas_number": "67-68-5",
        "molecular_formula": "C2H6OS",
        "molecular_weight": 78.13,
        "smiles": "CS(=O)C",
        "inchi": "InChI=1S/C2H6OS/c1-4(2)3/h1-2H3",
        "inchi_key": "IAZDPXIOMUYVGZ-UHFFFAOYSA-N",
        "density": 1.100,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": 18.5,
        "boiling_point_c": 189.0,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
    },
    {
        "name": "1,4-Dioxane",
        "iupac_name": "1,4-dioxane",
        "cas_number": "123-91-1",
        "molecular_formula": "C4H8O2",
        "molecular_weight": 88.11,
        "smiles": "C1COCCO1",
        "inchi": "InChI=1S/C4H8O2/c1-2-6-4-3-5-1/h1-4H2",
        "inchi_key": "RYHBNJHYFVUHQT-UHFFFAOYSA-N",
        "density": 1.034,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": 11.8,
        "boiling_point_c": 101.1,
        "ghs_pictograms": ["GHS02", "GHS07", "GHS08"],
        "h_phrases": ["H225", "H319", "H335", "H351"],
        "p_phrases": ["P210", "P280", "P305", "P338"],
    },
    {
        "name": "Pyridine",
        "iupac_name": "pyridine",
        "cas_number": "110-86-1",
        "molecular_formula": "C5H5N",
        "molecular_weight": 79.10,
        "smiles": "c1ccncc1",
        "inchi": "InChI=1S/C5H5N/c1-2-4-6-5-3-1/h1-5H",
        "inchi_key": "JUJWROOIHBZHMG-UHFFFAOYSA-N",
        "density": 0.982,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": -41.6,
        "boiling_point_c": 115.2,
        "ghs_pictograms": ["GHS02", "GHS07"],
        "h_phrases": ["H225", "H302", "H312", "H332"],
        "p_phrases": ["P210", "P280"],
    },
    # ─── Acids and bases ──────────────────────────────────────────────────────
    {
        "name": "Acetic acid",
        "iupac_name": "acetic acid",
        "cas_number": "64-19-7",
        "molecular_formula": "C2H4O2",
        "molecular_weight": 60.05,
        "smiles": "CC(=O)O",
        "inchi": "InChI=1S/C2H4O2/c1-2(3)4/h1H3,(H,3,4)",
        "inchi_key": "QTBSBXVTEAMEQO-UHFFFAOYSA-N",
        "density": 1.049,
        "state": "liquid",
        "is_solvent": True,
        "melting_point_c": 16.6,
        "boiling_point_c": 118.0,
        "ghs_pictograms": ["GHS02", "GHS05"],
        "h_phrases": ["H226", "H314"],
        "p_phrases": ["P210", "P280", "P301", "P305", "P338"],
    },
    {
        "name": "TFA",
        "iupac_name": "trifluoroacetic acid",
        "cas_number": "76-05-1",
        "molecular_formula": "C2HF3O2",
        "molecular_weight": 114.02,
        "smiles": "C(=O)(C(F)(F)F)O",
        "inchi": "InChI=1S/C2HF3O2/c3-2(4,5)1(6)7/h(H,6,7)",
        "inchi_key": "DTQVDTLACAAQTR-UHFFFAOYSA-N",
        "density": 1.489,
        "state": "liquid",
        "is_solvent": False,
        "melting_point_c": -15.4,
        "boiling_point_c": 72.4,
        "ghs_pictograms": ["GHS05", "GHS06", "GHS09"],
        "h_phrases": ["H314", "H332", "H412"],
        "p_phrases": ["P260", "P280", "P305", "P338"],
    },
    {
        "name": "Triethylamine",
        "iupac_name": "N,N-diethylethanamine",
        "cas_number": "121-44-8",
        "molecular_formula": "C6H15N",
        "molecular_weight": 101.19,
        "smiles": "CCN(CC)CC",
        "inchi": "InChI=1S/C6H15N/c1-4-7(5-2)6-3/h4-6H2,1-3H3",
        "inchi_key": "ZMANZCXQSJIPKH-UHFFFAOYSA-N",
        "density": 0.726,
        "state": "liquid",
        "is_solvent": False,
        "melting_point_c": -114.7,
        "boiling_point_c": 89.7,
        "ghs_pictograms": ["GHS02", "GHS05", "GHS06"],
        "h_phrases": ["H225", "H302", "H311", "H314", "H332"],
        "p_phrases": ["P210", "P280", "P305", "P338"],
    },
    {
        "name": "Sodium hydroxide",
        "iupac_name": "sodium hydroxide",
        "cas_number": "1310-73-2",
        "molecular_formula": "NaOH",
        "molecular_weight": 39.997,
        "smiles": "[Na+].[OH-]",
        "inchi": "InChI=1S/Na.H2O/h;1H2/q+1;/p-1",
        "inchi_key": "HEMHJVSKTPXQMS-UHFFFAOYSA-M",
        "density": 2.13,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 318.0,
        "boiling_point_c": 1388.0,
        "ghs_pictograms": ["GHS05"],
        "h_phrases": ["H290", "H314"],
        "p_phrases": ["P280", "P305", "P338"],
    },
    {
        "name": "Sodium bicarbonate",
        "iupac_name": "sodium hydrogen carbonate",
        "cas_number": "144-55-8",
        "molecular_formula": "CHNaO3",
        "molecular_weight": 84.007,
        "smiles": "C(=O)(O)[O-].[Na+]",
        "inchi": "InChI=1S/CH2O3.Na/c2-1(3)4;/h(H2,2,3,4);/q;+1/p-1",
        "inchi_key": "UIIMBOGNXHQVGW-UHFFFAOYSA-M",
        "density": 2.20,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 50.0,
        "boiling_point_c": None,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
    },
    {
        "name": "Sodium sulfate (anhydrous)",
        "iupac_name": "disodium sulfate",
        "cas_number": "7757-82-6",
        "molecular_formula": "Na2O4S",
        "molecular_weight": 142.04,
        "smiles": "[O-]S(=O)(=O)[O-].[Na+].[Na+]",
        "inchi": "InChI=1S/2Na.H2O4S/c;;1-5(2,3)4/h;;(H2,1,2,3,4)/q2*+1;/p-2",
        "inchi_key": "PMZURENOXWZQFD-UHFFFAOYSA-L",
        "density": 2.66,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 884.0,
        "boiling_point_c": 1429.0,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
        "notes": "Common drying agent for organic solutions.",
    },
    {
        "name": "Magnesium sulfate (anhydrous)",
        "iupac_name": "magnesium sulfate",
        "cas_number": "7487-88-9",
        "molecular_formula": "MgO4S",
        "molecular_weight": 120.37,
        "smiles": "[O-]S(=O)(=O)[O-].[Mg+2]",
        "inchi": "InChI=1S/Mg.H2O4S/c;1-5(2,3)4/h;(H2,1,2,3,4)/q+2;/p-2",
        "inchi_key": "CSNNHWWHGAXBCP-UHFFFAOYSA-L",
        "density": 2.66,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 1124.0,
        "boiling_point_c": None,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
        "notes": "Common drying agent for organic solutions.",
    },
    {
        "name": "Potassium carbonate",
        "iupac_name": "dipotassium carbonate",
        "cas_number": "584-08-7",
        "molecular_formula": "CK2O3",
        "molecular_weight": 138.21,
        "smiles": "C(=O)([O-])[O-].[K+].[K+]",
        "inchi": "InChI=1S/CH2O3.2K/c2-1(3)4;;/h(H2,2,3,4);;/q;2*+1/p-2",
        "inchi_key": "BWHMMNNQKKPAPP-UHFFFAOYSA-L",
        "density": 2.43,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 891.0,
        "boiling_point_c": None,
        "ghs_pictograms": ["GHS07"],
        "h_phrases": ["H315", "H319", "H335"],
        "p_phrases": ["P261", "P305", "P338"],
    },
    {
        "name": "Ammonium chloride",
        "iupac_name": "ammonium chloride",
        "cas_number": "12125-02-9",
        "molecular_formula": "ClH4N",
        "molecular_weight": 53.49,
        "smiles": "[NH4+].[Cl-]",
        "inchi": "InChI=1S/ClH.H3N/h1H;1H3",
        "inchi_key": "NLXLAEXVIDQMFP-UHFFFAOYSA-N",
        "density": 1.527,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 338.0,
        "boiling_point_c": 520.0,
        "ghs_pictograms": ["GHS07"],
        "h_phrases": ["H302", "H319"],
        "p_phrases": ["P305", "P338"],
    },
    # ─── Catalysts and reagents ────────────────────────────────────────────────
    {
        "name": "Aluminum chloride",
        "iupac_name": "aluminum trichloride",
        "cas_number": "7446-70-0",
        "molecular_formula": "AlCl3",
        "molecular_weight": 133.34,
        "smiles": "[Al+3].[Cl-].[Cl-].[Cl-]",
        "inchi": "InChI=1S/Al.3ClH/h;3*1H/q+3;;;/p-3",
        "inchi_key": "VSCWAEJMTAWNJL-UHFFFAOYSA-K",
        "density": 2.48,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 192.6,
        "boiling_point_c": 180.0,
        "ghs_pictograms": ["GHS05"],
        "h_phrases": ["H314", "EUH014"],
        "p_phrases": ["P280", "P305", "P338"],
        "notes": "Lewis acid for Friedel-Crafts. Highly hygroscopic — fume hood + dry.",
    },
    {
        "name": "Iron(III) chloride",
        "iupac_name": "iron trichloride",
        "cas_number": "7705-08-0",
        "molecular_formula": "Cl3Fe",
        "molecular_weight": 162.20,
        "smiles": "Cl[Fe](Cl)Cl",
        "inchi": "InChI=1S/3ClH.Fe/h3*1H;/q;;;+3/p-3",
        "inchi_key": "RBTARNINKXHZNM-UHFFFAOYSA-K",
        "density": 2.90,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 306.0,
        "boiling_point_c": 316.0,
        "ghs_pictograms": ["GHS05", "GHS07"],
        "h_phrases": ["H290", "H302", "H315", "H318"],
        "p_phrases": ["P280", "P305", "P338"],
    },
    {
        "name": "Palladium on carbon (10%)",
        "iupac_name": "palladium",
        "cas_number": "7440-05-3",
        "molecular_formula": "Pd",
        "molecular_weight": 106.42,
        "smiles": "[Pd]",
        "inchi": "InChI=1S/Pd",
        "inchi_key": "KDLHZDBZIXYQEI-UHFFFAOYSA-N",
        "density": 12.02,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 1554.9,
        "boiling_point_c": 2963.0,
        "ghs_pictograms": ["GHS02"],
        "h_phrases": ["H228"],
        "p_phrases": ["P210", "P280"],
        "notes": "Hydrogenation catalyst. Pyrophoric when dry. Wet with water before disposal.",
    },
    {
        "name": "Copper(I) iodide",
        "iupac_name": "copper iodide",
        "cas_number": "7681-65-4",
        "molecular_formula": "CuI",
        "molecular_weight": 190.45,
        "smiles": "I[Cu]",
        "inchi": "InChI=1S/Cu.HI/h;1H/q+1;/p-1",
        "inchi_key": "LSXDOTMGLUJQCM-UHFFFAOYSA-M",
        "density": 5.67,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 605.0,
        "boiling_point_c": 1290.0,
        "ghs_pictograms": ["GHS07", "GHS09"],
        "h_phrases": ["H315", "H319", "H335", "H410"],
        "p_phrases": ["P261", "P273", "P305", "P338"],
    },
    {
        "name": "Silica gel",
        "iupac_name": "silicon dioxide",
        "cas_number": "7631-86-9",
        "molecular_formula": "SiO2",
        "molecular_weight": 60.08,
        "smiles": "O=[Si]=O",
        "inchi": "InChI=1S/O2Si/c1-3-2",
        "inchi_key": "VYPSYNLAJGMNEJ-UHFFFAOYSA-N",
        "density": 2.20,
        "state": "solid",
        "is_solvent": False,
        "melting_point_c": 1713.0,
        "boiling_point_c": 2950.0,
        "ghs_pictograms": [],
        "h_phrases": [],
        "p_phrases": [],
        "notes": "Standard column chromatography stationary phase.",
    },
]
