"""Stoic ELN — Seed data for GHS hazard phrases.

Comprehensive CLP Regulation Annex III (H + EUH phrases) + Annex IV (P phrases).
Texts are the official ECHA versions in English and Italian.

To extend: add entries below; the seed routine will skip codes that already
exist in the database (idempotent).

Sources:
- https://eur-lex.europa.eu/eli/reg/2008/1272/oj  (CLP Regulation, EN+IT)
- https://echa.europa.eu/regulations/clp/clp-translation
"""

# Format: (code, category, en, it)
HAZARD_PHRASES: list[tuple[str, str, str, str]] = [
    # ─── Physical hazards (H2xx) ──────────────────────────────────────────────
    ("H200", "H", "Unstable explosive.", "Esplosivo instabile."),
    (
        "H201",
        "H",
        "Explosive; mass explosion hazard.",
        "Esplosivo; pericolo di esplosione di massa.",
    ),
    (
        "H202",
        "H",
        "Explosive; severe projection hazard.",
        "Esplosivo; grave pericolo di proiezione.",
    ),
    (
        "H203",
        "H",
        "Explosive; fire, blast or projection hazard.",
        "Esplosivo; pericolo di incendio, di spostamento d'aria o di proiezione.",
    ),
    ("H204", "H", "Fire or projection hazard.", "Pericolo di incendio o di proiezione."),
    (
        "H205",
        "H",
        "May mass explode in fire.",
        "Pericolo di esplosione di massa in caso d'incendio.",
    ),
    (
        "H206",
        "H",
        "Fire, blast or projection hazard; increased risk of explosion if desensitising agent is reduced.",
        "Pericolo di incendio, di spostamento d'aria o di proiezione; maggiore rischio di esplosione se l'agente desensibilizzante è diminuito.",
    ),
    (
        "H207",
        "H",
        "Fire or projection hazard; increased risk of explosion if desensitising agent is reduced.",
        "Pericolo di incendio o di proiezione; maggiore rischio di esplosione se l'agente desensibilizzante è diminuito.",
    ),
    (
        "H208",
        "H",
        "Fire hazard; increased risk of explosion if desensitising agent is reduced.",
        "Pericolo di incendio; maggiore rischio di esplosione se l'agente desensibilizzante è diminuito.",
    ),
    ("H220", "H", "Extremely flammable gas.", "Gas altamente infiammabile."),
    ("H221", "H", "Flammable gas.", "Gas infiammabile."),
    ("H222", "H", "Extremely flammable aerosol.", "Aerosol altamente infiammabile."),
    ("H223", "H", "Flammable aerosol.", "Aerosol infiammabile."),
    (
        "H224",
        "H",
        "Extremely flammable liquid and vapour.",
        "Liquido e vapori altamente infiammabili.",
    ),
    (
        "H225",
        "H",
        "Highly flammable liquid and vapour.",
        "Liquido e vapori facilmente infiammabili.",
    ),
    ("H226", "H", "Flammable liquid and vapour.", "Liquido e vapori infiammabili."),
    ("H228", "H", "Flammable solid.", "Solido infiammabile."),
    (
        "H229",
        "H",
        "Pressurised container: may burst if heated.",
        "Contenitore pressurizzato: può esplodere se riscaldato.",
    ),
    (
        "H230",
        "H",
        "May react explosively even in the absence of air.",
        "Può esplodere anche in assenza di aria.",
    ),
    (
        "H231",
        "H",
        "May react explosively even in the absence of air at elevated pressure and/or temperature.",
        "Può esplodere anche in assenza di aria a pressione e/o temperatura elevata.",
    ),
    (
        "H232",
        "H",
        "May ignite spontaneously if exposed to air.",
        "Spontaneamente infiammabile se esposto all'aria.",
    ),
    ("H240", "H", "Heating may cause an explosion.", "Rischio di esplosione per riscaldamento."),
    (
        "H241",
        "H",
        "Heating may cause a fire or explosion.",
        "Rischio d'incendio o di esplosione per riscaldamento.",
    ),
    ("H242", "H", "Heating may cause a fire.", "Il riscaldamento può provocare un incendio."),
    (
        "H250",
        "H",
        "Catches fire spontaneously if exposed to air.",
        "Spontaneamente infiammabile all'aria.",
    ),
    ("H251", "H", "Self-heating; may catch fire.", "Autoriscaldante; può infiammarsi."),
    (
        "H252",
        "H",
        "Self-heating in large quantities; may catch fire.",
        "Autoriscaldante in grandi quantità; può infiammarsi.",
    ),
    (
        "H260",
        "H",
        "In contact with water releases flammable gases which may ignite spontaneously.",
        "A contatto con l'acqua libera gas infiammabili che possono infiammarsi spontaneamente.",
    ),
    (
        "H261",
        "H",
        "In contact with water releases flammable gases.",
        "A contatto con l'acqua libera gas infiammabili.",
    ),
    (
        "H270",
        "H",
        "May cause or intensify fire; oxidiser.",
        "Può provocare o aggravare un incendio; comburente.",
    ),
    (
        "H271",
        "H",
        "May cause fire or explosion; strong oxidiser.",
        "Può provocare un incendio o un'esplosione; molto comburente.",
    ),
    ("H272", "H", "May intensify fire; oxidiser.", "Può aggravare un incendio; comburente."),
    (
        "H280",
        "H",
        "Contains gas under pressure; may explode if heated.",
        "Contiene gas sotto pressione; può esplodere se riscaldato.",
    ),
    (
        "H281",
        "H",
        "Contains refrigerated gas; may cause cryogenic burns or injury.",
        "Contiene gas refrigerato; può provocare ustioni o lesioni criogeniche.",
    ),
    ("H290", "H", "May be corrosive to metals.", "Può essere corrosivo per i metalli."),
    # ─── Health hazards (H3xx) ────────────────────────────────────────────────
    ("H300", "H", "Fatal if swallowed.", "Letale se ingerito."),
    ("H301", "H", "Toxic if swallowed.", "Tossico se ingerito."),
    ("H302", "H", "Harmful if swallowed.", "Nocivo se ingerito."),
    (
        "H304",
        "H",
        "May be fatal if swallowed and enters airways.",
        "Può essere letale in caso di ingestione e di penetrazione nelle vie respiratorie.",
    ),
    (
        "H305",
        "H",
        "May be harmful if swallowed and enters airways.",
        "Può essere nocivo in caso di ingestione e di penetrazione nelle vie respiratorie.",
    ),
    ("H310", "H", "Fatal in contact with skin.", "Letale per contatto con la pelle."),
    ("H311", "H", "Toxic in contact with skin.", "Tossico per contatto con la pelle."),
    ("H312", "H", "Harmful in contact with skin.", "Nocivo per contatto con la pelle."),
    (
        "H314",
        "H",
        "Causes severe skin burns and eye damage.",
        "Provoca gravi ustioni cutanee e gravi lesioni oculari.",
    ),
    ("H315", "H", "Causes skin irritation.", "Provoca irritazione cutanea."),
    ("H316", "H", "Causes mild skin irritation.", "Provoca lieve irritazione cutanea."),
    (
        "H317",
        "H",
        "May cause an allergic skin reaction.",
        "Può provocare una reazione allergica cutanea.",
    ),
    ("H318", "H", "Causes serious eye damage.", "Provoca gravi lesioni oculari."),
    ("H319", "H", "Causes serious eye irritation.", "Provoca grave irritazione oculare."),
    ("H320", "H", "Causes eye irritation.", "Provoca irritazione oculare."),
    ("H330", "H", "Fatal if inhaled.", "Letale se inalato."),
    ("H331", "H", "Toxic if inhaled.", "Tossico se inalato."),
    ("H332", "H", "Harmful if inhaled.", "Nocivo se inalato."),
    (
        "H334",
        "H",
        "May cause allergy or asthma symptoms or breathing difficulties if inhaled.",
        "Può provocare sintomi allergici o asmatici o difficoltà respiratorie se inalato.",
    ),
    ("H335", "H", "May cause respiratory irritation.", "Può irritare le vie respiratorie."),
    ("H336", "H", "May cause drowsiness or dizziness.", "Può provocare sonnolenza o vertigini."),
    ("H340", "H", "May cause genetic defects.", "Può provocare alterazioni genetiche."),
    (
        "H341",
        "H",
        "Suspected of causing genetic defects.",
        "Sospettato di provocare alterazioni genetiche.",
    ),
    ("H350", "H", "May cause cancer.", "Può provocare il cancro."),
    ("H350i", "H", "May cause cancer by inhalation.", "Può provocare il cancro se inalato."),
    ("H351", "H", "Suspected of causing cancer.", "Sospettato di provocare il cancro."),
    (
        "H360",
        "H",
        "May damage fertility or the unborn child.",
        "Può nuocere alla fertilità o al feto.",
    ),
    ("H360F", "H", "May damage fertility.", "Può nuocere alla fertilità."),
    ("H360D", "H", "May damage the unborn child.", "Può nuocere al feto."),
    (
        "H360FD",
        "H",
        "May damage fertility. May damage the unborn child.",
        "Può nuocere alla fertilità. Può nuocere al feto.",
    ),
    (
        "H360Fd",
        "H",
        "May damage fertility. Suspected of damaging the unborn child.",
        "Può nuocere alla fertilità. Sospettato di nuocere al feto.",
    ),
    (
        "H360Df",
        "H",
        "May damage the unborn child. Suspected of damaging fertility.",
        "Può nuocere al feto. Sospettato di nuocere alla fertilità.",
    ),
    (
        "H361",
        "H",
        "Suspected of damaging fertility or the unborn child.",
        "Sospettato di nuocere alla fertilità o al feto.",
    ),
    ("H361f", "H", "Suspected of damaging fertility.", "Sospettato di nuocere alla fertilità."),
    ("H361d", "H", "Suspected of damaging the unborn child.", "Sospettato di nuocere al feto."),
    (
        "H361fd",
        "H",
        "Suspected of damaging fertility. Suspected of damaging the unborn child.",
        "Sospettato di nuocere alla fertilità. Sospettato di nuocere al feto.",
    ),
    (
        "H362",
        "H",
        "May cause harm to breast-fed children.",
        "Può essere nocivo per i lattanti allattati al seno.",
    ),
    ("H370", "H", "Causes damage to organs.", "Provoca danni agli organi."),
    ("H371", "H", "May cause damage to organs.", "Può provocare danni agli organi."),
    (
        "H372",
        "H",
        "Causes damage to organs through prolonged or repeated exposure.",
        "Provoca danni agli organi in caso di esposizione prolungata o ripetuta.",
    ),
    (
        "H373",
        "H",
        "May cause damage to organs through prolonged or repeated exposure.",
        "Può provocare danni agli organi in caso di esposizione prolungata o ripetuta.",
    ),
    # ─── Environmental hazards (H4xx) ─────────────────────────────────────────
    ("H400", "H", "Very toxic to aquatic life.", "Molto tossico per gli organismi acquatici."),
    (
        "H410",
        "H",
        "Very toxic to aquatic life with long lasting effects.",
        "Molto tossico per gli organismi acquatici con effetti di lunga durata.",
    ),
    (
        "H411",
        "H",
        "Toxic to aquatic life with long lasting effects.",
        "Tossico per gli organismi acquatici con effetti di lunga durata.",
    ),
    (
        "H412",
        "H",
        "Harmful to aquatic life with long lasting effects.",
        "Nocivo per gli organismi acquatici con effetti di lunga durata.",
    ),
    (
        "H413",
        "H",
        "May cause long lasting harmful effects to aquatic life.",
        "Può essere nocivo per gli organismi acquatici con effetti di lunga durata.",
    ),
    (
        "H420",
        "H",
        "Harms public health and the environment by destroying ozone in the upper atmosphere.",
        "Nuoce alla salute pubblica e all'ambiente distruggendo l'ozono dell'atmosfera superiore.",
    ),
    # ─── EUH supplementary phrases ────────────────────────────────────────────
    ("EUH001", "EUH", "Explosive when dry.", "Esplosivo allo stato secco."),
    ("EUH014", "EUH", "Reacts violently with water.", "Reagisce violentemente con l'acqua."),
    (
        "EUH018",
        "EUH",
        "In use may form flammable/explosive vapour-air mixture.",
        "Durante l'uso può formarsi una miscela vapore-aria esplosiva/infiammabile.",
    ),
    ("EUH019", "EUH", "May form explosive peroxides.", "Può formare perossidi esplosivi."),
    (
        "EUH029",
        "EUH",
        "Contact with water liberates toxic gas.",
        "A contatto con l'acqua libera gas tossici.",
    ),
    (
        "EUH031",
        "EUH",
        "Contact with acids liberates toxic gas.",
        "A contatto con acidi libera gas tossici.",
    ),
    (
        "EUH032",
        "EUH",
        "Contact with acids liberates very toxic gas.",
        "A contatto con acidi libera gas altamente tossici.",
    ),
    (
        "EUH044",
        "EUH",
        "Risk of explosion if heated under confinement.",
        "Rischio di esplosione per riscaldamento in ambiente confinato.",
    ),
    ("EUH059", "EUH", "Hazardous to the ozone layer.", "Pericoloso per lo strato di ozono."),
    (
        "EUH066",
        "EUH",
        "Repeated exposure may cause skin dryness or cracking.",
        "L'esposizione ripetuta può provocare secchezza o screpolature della pelle.",
    ),
    ("EUH070", "EUH", "Toxic by eye contact.", "Tossico per contatto oculare."),
    ("EUH071", "EUH", "Corrosive to the respiratory tract.", "Corrosivo per le vie respiratorie."),
    (
        "EUH201",
        "EUH",
        "Contains lead. Should not be used on surfaces liable to be chewed or sucked by children.",
        "Contiene piombo. Non utilizzare su oggetti suscettibili di essere masticati o succhiati dai bambini.",
    ),
    (
        "EUH202",
        "EUH",
        "Cyanoacrylate. Danger. Bonds skin and eyes in seconds. Keep out of reach of children.",
        "Cianoacrilato. Pericolo. Incolla la pelle e gli occhi in pochi secondi. Tenere fuori dalla portata dei bambini.",
    ),
    (
        "EUH203",
        "EUH",
        "Contains chromium (VI). May produce an allergic reaction.",
        "Contiene cromo (VI). Può provocare una reazione allergica.",
    ),
    (
        "EUH204",
        "EUH",
        "Contains isocyanates. May produce an allergic reaction.",
        "Contiene isocianati. Può provocare una reazione allergica.",
    ),
    (
        "EUH205",
        "EUH",
        "Contains epoxy constituents. May produce an allergic reaction.",
        "Contiene componenti epossidici. Può provocare una reazione allergica.",
    ),
    (
        "EUH206",
        "EUH",
        "Warning! Do not use together with other products. May release dangerous gases (chlorine).",
        "Attenzione! Non utilizzare in combinazione con altri prodotti. Possono liberarsi gas pericolosi (cloro).",
    ),
    (
        "EUH207",
        "EUH",
        "Warning! Contains cadmium. Dangerous fumes are formed during use. See information supplied by the manufacturer. Comply with the safety instructions.",
        "Attenzione! Contiene cadmio. Durante l'uso si sviluppano fumi pericolosi. Leggere le informazioni fornite dal fabbricante. Rispettare le disposizioni di sicurezza.",
    ),
    (
        "EUH208",
        "EUH",
        "Contains [name of sensitising substance]. May produce an allergic reaction.",
        "Contiene [nome della sostanza sensibilizzante]. Può provocare una reazione allergica.",
    ),
    (
        "EUH209",
        "EUH",
        "Can become highly flammable in use.",
        "Può diventare facilmente infiammabile durante l'uso.",
    ),
    ("EUH209A", "EUH", "Can become flammable in use.", "Può diventare infiammabile durante l'uso."),
    (
        "EUH210",
        "EUH",
        "Safety data sheet available on request.",
        "Scheda dati di sicurezza disponibile su richiesta.",
    ),
    (
        "EUH211",
        "EUH",
        "Warning! Hazardous respirable droplets may be formed when sprayed. Do not breathe spray or mist.",
        "Attenzione! In caso di vaporizzazione possono formarsi goccioline pericolose. Non respirare i vapori o le nebbie.",
    ),
    (
        "EUH212",
        "EUH",
        "Warning! Hazardous respirable dust may be formed when used. Do not breathe dust.",
        "Attenzione! In caso d'uso può formarsi polvere pericolosa. Non respirare la polvere.",
    ),
    (
        "EUH401",
        "EUH",
        "To avoid risks to human health and the environment, comply with the instructions for use.",
        "Per evitare rischi per la salute umana e per l'ambiente, seguire le istruzioni per l'uso.",
    ),
    # ─── Precautionary statements: General (P1xx) ─────────────────────────────
    (
        "P101",
        "P",
        "If medical advice is needed, have product container or label at hand.",
        "In caso di consultazione di un medico, tenere a disposizione il contenitore o l'etichetta del prodotto.",
    ),
    ("P102", "P", "Keep out of reach of children.", "Tenere fuori dalla portata dei bambini."),
    (
        "P103",
        "P",
        "Read carefully and follow all instructions.",
        "Leggere attentamente e seguire tutte le istruzioni.",
    ),
    # ─── Precautionary: Prevention (P2xx) ─────────────────────────────────────
    (
        "P201",
        "P",
        "Obtain special instructions before use.",
        "Procurarsi istruzioni specifiche prima dell'uso.",
    ),
    (
        "P202",
        "P",
        "Do not handle until all safety precautions have been read and understood.",
        "Non manipolare prima di aver letto e compreso tutte le avvertenze.",
    ),
    (
        "P210",
        "P",
        "Keep away from heat, hot surfaces, sparks, open flames and other ignition sources. No smoking.",
        "Tenere lontano da fonti di calore, superfici calde, scintille, fiamme libere o altre fonti di accensione. Non fumare.",
    ),
    (
        "P211",
        "P",
        "Do not spray on an open flame or other ignition source.",
        "Non vaporizzare su una fiamma libera o altra fonte di accensione.",
    ),
    (
        "P212",
        "P",
        "Avoid heating under confinement or reduction of the desensitising agent.",
        "Evitare il riscaldamento in ambiente confinato o la riduzione dell'agente desensibilizzante.",
    ),
    (
        "P220",
        "P",
        "Keep away from clothing and other combustible materials.",
        "Tenere lontano da indumenti e altri materiali combustibili.",
    ),
    ("P222", "P", "Do not allow contact with air.", "Evitare il contatto con l'aria."),
    ("P223", "P", "Do not allow contact with water.", "Evitare il contatto con l'acqua."),
    ("P230", "P", "Keep wetted with...", "Mantenere umido con..."),
    (
        "P231",
        "P",
        "Handle and store contents under inert gas/...",
        "Manipolare e conservare il contenuto sotto gas inerte/...",
    ),
    ("P232", "P", "Protect from moisture.", "Proteggere dall'umidità."),
    ("P233", "P", "Keep container tightly closed.", "Tenere il recipiente ben chiuso."),
    (
        "P234",
        "P",
        "Keep only in original packaging.",
        "Conservare soltanto nell'imballaggio originale.",
    ),
    ("P235", "P", "Keep cool.", "Tenere in luogo fresco."),
    (
        "P240",
        "P",
        "Ground and bond container and receiving equipment.",
        "Mettere a terra e a massa il contenitore e il dispositivo ricevente.",
    ),
    (
        "P241",
        "P",
        "Use explosion-proof electrical/ventilating/lighting equipment.",
        "Utilizzare impianti elettrici/di ventilazione/d'illuminazione antideflagranti.",
    ),
    ("P242", "P", "Use non-sparking tools.", "Utilizzare utensili antiscintillamento."),
    (
        "P243",
        "P",
        "Take action to prevent static discharges.",
        "Fare il necessario per impedire le scariche elettrostatiche.",
    ),
    (
        "P244",
        "P",
        "Keep valves and fittings free from oil and grease.",
        "Mantenere le valvole di riduzione libere da grasso e olio.",
    ),
    (
        "P250",
        "P",
        "Do not subject to grinding/shock/friction/...",
        "Evitare le abrasioni/gli urti/lo sfregamento/...",
    ),
    (
        "P251",
        "P",
        "Do not pierce or burn, even after use.",
        "Non perforare né bruciare, neppure dopo l'uso.",
    ),
    (
        "P260",
        "P",
        "Do not breathe dust/fume/gas/mist/vapours/spray.",
        "Non respirare la polvere/i fumi/i gas/la nebbia/i vapori/gli aerosol.",
    ),
    (
        "P261",
        "P",
        "Avoid breathing dust/fume/gas/mist/vapours/spray.",
        "Evitare di respirare la polvere/i fumi/i gas/la nebbia/i vapori/gli aerosol.",
    ),
    (
        "P262",
        "P",
        "Do not get in eyes, on skin, or on clothing.",
        "Evitare il contatto con gli occhi, la pelle o gli indumenti.",
    ),
    (
        "P263",
        "P",
        "Avoid contact during pregnancy and while nursing.",
        "Evitare il contatto durante la gravidanza e l'allattamento.",
    ),
    ("P264", "P", "Wash thoroughly after handling.", "Lavare accuratamente dopo l'uso."),
    ("P265", "P", "Do not touch eyes.", "Non toccare gli occhi."),
    (
        "P270",
        "P",
        "Do not eat, drink or smoke when using this product.",
        "Non mangiare, né bere, né fumare durante l'uso.",
    ),
    (
        "P271",
        "P",
        "Use only outdoors or in a well-ventilated area.",
        "Utilizzare soltanto all'aperto o in luogo ben ventilato.",
    ),
    (
        "P272",
        "P",
        "Contaminated work clothing should not be allowed out of the workplace.",
        "Gli indumenti da lavoro contaminati non devono essere portati fuori dal luogo di lavoro.",
    ),
    ("P273", "P", "Avoid release to the environment.", "Non disperdere nell'ambiente."),
    (
        "P280",
        "P",
        "Wear protective gloves/protective clothing/eye protection/face protection.",
        "Indossare guanti/indumenti protettivi/Proteggere gli occhi/il viso.",
    ),
    (
        "P282",
        "P",
        "Wear cold insulating gloves and either face shield or eye protection.",
        "Utilizzare guanti termici e schermo facciale o protezione per gli occhi.",
    ),
    (
        "P283",
        "P",
        "Wear fire resistant or flame retardant clothing.",
        "Indossare indumenti resistenti al fuoco o alla fiamma.",
    ),
    (
        "P284",
        "P",
        "[In case of inadequate ventilation] wear respiratory protection.",
        "[Quando la ventilazione è insufficiente] indossare un apparecchio di protezione respiratoria.",
    ),
    (
        "P285",
        "P",
        "In case of inadequate ventilation wear respiratory protection.",
        "In caso di ventilazione insufficiente utilizzare un apparecchio di protezione respiratoria.",
    ),
    # ─── Precautionary: Response (P3xx) ───────────────────────────────────────
    ("P301", "P", "IF SWALLOWED:", "IN CASO DI INGESTIONE:"),
    ("P302", "P", "IF ON SKIN:", "IN CASO DI CONTATTO CON LA PELLE:"),
    ("P303", "P", "IF ON SKIN (or hair):", "IN CASO DI CONTATTO CON LA PELLE (o con i capelli):"),
    ("P304", "P", "IF INHALED:", "IN CASO DI INALAZIONE:"),
    ("P305", "P", "IF IN EYES:", "IN CASO DI CONTATTO CON GLI OCCHI:"),
    ("P306", "P", "IF ON CLOTHING:", "IN CASO DI CONTATTO CON GLI INDUMENTI:"),
    ("P308", "P", "IF exposed or concerned:", "IN CASO di esposizione o di malessere:"),
    (
        "P310",
        "P",
        "Immediately call a POISON CENTER/doctor.",
        "Contattare immediatamente un CENTRO ANTIVELENI/un medico.",
    ),
    ("P311", "P", "Call a POISON CENTER/doctor.", "Contattare un CENTRO ANTIVELENI/un medico."),
    (
        "P312",
        "P",
        "Call a POISON CENTER/doctor if you feel unwell.",
        "Contattare un CENTRO ANTIVELENI/un medico in caso di malessere.",
    ),
    ("P313", "P", "Get medical advice/attention.", "Consultare un medico."),
    (
        "P314",
        "P",
        "Get medical advice/attention if you feel unwell.",
        "In caso di malessere, consultare un medico.",
    ),
    (
        "P315",
        "P",
        "Get immediate medical advice/attention.",
        "Consultare immediatamente un medico.",
    ),
    (
        "P316",
        "P",
        "Get emergency medical help immediately.",
        "Richiedere immediatamente assistenza medica d'emergenza.",
    ),
    ("P317", "P", "Get medical help.", "Consultare un medico."),
    (
        "P318",
        "P",
        "If exposed or concerned, get medical advice.",
        "In caso di esposizione o malessere, consultare un medico.",
    ),
    (
        "P319",
        "P",
        "Get medical help if you feel unwell.",
        "Consultare un medico in caso di malessere.",
    ),
    (
        "P320",
        "P",
        "Specific treatment is urgent (see ... on this label).",
        "È urgente un trattamento specifico (vedere ... su questa etichetta).",
    ),
    (
        "P321",
        "P",
        "Specific treatment (see ... on this label).",
        "Trattamento specifico (vedere ... su questa etichetta).",
    ),
    (
        "P322",
        "P",
        "Specific measures (see ... on this label).",
        "Misure specifiche (vedere ... su questa etichetta).",
    ),
    ("P330", "P", "Rinse mouth.", "Sciacquare la bocca."),
    ("P331", "P", "Do NOT induce vomiting.", "NON provocare il vomito."),
    ("P332", "P", "If skin irritation occurs:", "In caso di irritazione della pelle:"),
    (
        "P333",
        "P",
        "If skin irritation or rash occurs:",
        "In caso di irritazione o eruzione della pelle:",
    ),
    (
        "P334",
        "P",
        "Immerse in cool water [or wrap in wet bandages].",
        "Immergere in acqua fredda [o avvolgere con un bendaggio umido].",
    ),
    (
        "P335",
        "P",
        "Brush off loose particles from skin.",
        "Rimuovere le particelle depositate sulla pelle.",
    ),
    (
        "P336",
        "P",
        "Thaw frosted parts with lukewarm water. Do not rub affected area.",
        "Sgelare le parti congelate usando acqua tiepida. Non sfregare la parte interessata.",
    ),
    ("P337", "P", "If eye irritation persists:", "Se l'irritazione degli occhi persiste:"),
    (
        "P338",
        "P",
        "Remove contact lenses, if present and easy to do. Continue rinsing.",
        "Togliere le eventuali lenti a contatto se è agevole farlo. Continuare a sciacquare.",
    ),
    (
        "P340",
        "P",
        "Remove person to fresh air and keep comfortable for breathing.",
        "Trasportare l'infortunato all'aria aperta e mantenerlo a riposo in posizione che favorisca la respirazione.",
    ),
    ("P342", "P", "If experiencing respiratory symptoms:", "In caso di sintomi respiratori:"),
    (
        "P351",
        "P",
        "Rinse cautiously with water for several minutes.",
        "Sciacquare accuratamente per parecchi minuti.",
    ),
    ("P352", "P", "Wash with plenty of water/...", "Lavare abbondantemente con acqua/..."),
    ("P353", "P", "Rinse skin with water [or shower].", "Sciacquare la pelle [o fare una doccia]."),
    (
        "P354",
        "P",
        "Immediately rinse with plenty of water.",
        "Sciacquare immediatamente e abbondantemente con acqua.",
    ),
    (
        "P360",
        "P",
        "Rinse immediately contaminated clothing and skin with plenty of water before removing clothes.",
        "Sciacquare immediatamente e abbondantemente gli indumenti contaminati e la pelle prima di togliersi gli indumenti.",
    ),
    (
        "P361",
        "P",
        "Take off immediately all contaminated clothing.",
        "Togliere immediatamente tutti gli indumenti contaminati.",
    ),
    ("P362", "P", "Take off contaminated clothing.", "Togliere gli indumenti contaminati."),
    (
        "P363",
        "P",
        "Wash contaminated clothing before reuse.",
        "Lavare gli indumenti contaminati prima di indossarli nuovamente.",
    ),
    ("P364", "P", "And wash it before reuse.", "E lavarli prima di indossarli nuovamente."),
    ("P370", "P", "In case of fire:", "In caso di incendio:"),
    (
        "P371",
        "P",
        "In case of major fire and large quantities:",
        "In caso di incendio grave e di grandi quantità:",
    ),
    ("P372", "P", "Explosion risk.", "Rischio di esplosione."),
    (
        "P373",
        "P",
        "DO NOT fight fire when fire reaches explosives.",
        "NON tentare di estinguere l'incendio se questo raggiunge materiali esplosivi.",
    ),
    (
        "P375",
        "P",
        "Fight fire remotely due to the risk of explosion.",
        "Rischio di esplosione. Spegnere l'incendio a distanza.",
    ),
    (
        "P377",
        "P",
        "Leaking gas fire: Do not extinguish, unless leak can be stopped safely.",
        "In caso d'incendio dovuto a perdita di gas, non estinguere a meno che non sia possibile bloccare la perdita senza pericolo.",
    ),
    (
        "P378",
        "P",
        "Use suitable extinguishing media.",
        "Utilizzare mezzi di estinzione appropriati.",
    ),
    ("P380", "P", "Evacuate area.", "Evacuare la zona."),
    (
        "P381",
        "P",
        "In case of leakage, eliminate all ignition sources.",
        "In caso di perdita, eliminare tutte le sorgenti di accensione.",
    ),
    (
        "P390",
        "P",
        "Absorb spillage to prevent material damage.",
        "Assorbire la fuoriuscita per evitare danni materiali.",
    ),
    ("P391", "P", "Collect spillage.", "Raccogliere il materiale fuoriuscito."),
    # ─── Precautionary: Storage (P4xx) ────────────────────────────────────────
    ("P401", "P", "Store in accordance with...", "Conservare conformemente a..."),
    ("P402", "P", "Store in a dry place.", "Conservare in luogo asciutto."),
    ("P403", "P", "Store in a well-ventilated place.", "Conservare in luogo ben ventilato."),
    ("P404", "P", "Store in a closed container.", "Conservare in un recipiente chiuso."),
    ("P405", "P", "Store locked up.", "Conservare sotto chiave."),
    (
        "P406",
        "P",
        "Store in corrosion resistant/... container with a resistant inner liner.",
        "Conservare in recipiente resistente alla corrosione/... provvisto di rivestimento interno resistente.",
    ),
    (
        "P407",
        "P",
        "Maintain air gap between stacks or pallets.",
        "Mantenere uno spazio libero tra gli scaffali o i pallet.",
    ),
    ("P410", "P", "Protect from sunlight.", "Proteggere dai raggi solari."),
    (
        "P411",
        "P",
        "Store at temperatures not exceeding ... °C/...°F.",
        "Conservare a temperature non superiori a ... °C/...°F.",
    ),
    (
        "P412",
        "P",
        "Do not expose to temperatures exceeding 50 °C/122 °F.",
        "Non esporre a temperature superiori a 50 °C/122 °F.",
    ),
    (
        "P413",
        "P",
        "Store bulk masses greater than ... kg/... lbs at temperatures not exceeding ... °C/...°F.",
        "Conservare le rinfuse di oltre ... kg/... lb a temperature non superiori a ... °C/...°F.",
    ),
    ("P420", "P", "Store separately.", "Conservare separatamente."),
    ("P422", "P", "Store contents under...", "Conservare il contenuto sotto..."),
    # ─── Precautionary: Disposal (P5xx) ───────────────────────────────────────
    (
        "P501",
        "P",
        "Dispose of contents/container in accordance with local/regional/national/international regulations.",
        "Smaltire il prodotto/recipiente in conformità alla normativa locale/regionale/nazionale/internazionale.",
    ),
    (
        "P502",
        "P",
        "Refer to manufacturer or supplier for information on recovery or recycling.",
        "Chiedere informazioni al fabbricante o fornitore in merito al recupero e al riciclaggio.",
    ),
    (
        "P503",
        "P",
        "Refer to manufacturer/supplier/... for information on disposal/recovery/recycling.",
        "Chiedere informazioni al fabbricante/fornitore/... per le indicazioni sullo smaltimento/recupero/riciclaggio.",
    ),
]
